AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: myHandler.handler
      Runtime: nodejs4.3
      CodeUri: 's3://mattfite-lambda-functions/myHandler.zip'
Outputs:
  LambdaFunctions:
    Value:
      Ref: MyFunction
