---
AWSTemplateFormatVersion: "2010-09-09"
Description: Create a security group.  Depends on the VPC created in the 
    accompanying directory, vpc.yaml. Exports the sg
Parameters:
  VPCStack:
    Type: String
Resources:
    mySG:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow ssh and http to host
            VpcId:
              Fn::ImportValue:
                !Sub "${VPCStack}-VPCID"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: '22'
              ToPort: '22'
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: '80'
              ToPort: '80'
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: '22'
              ToPort: '22'
              CidrIp: 0.0.0.0/0
            - IpProtocol: tcp
              FromPort: '80'
              ToPort: '80'
              CidrIp: 0.0.0.0/0
Outputs:
    StackSg:
        Description: The logical name of the security group
        Value: !Ref mySG
        Export:
            Name: !Sub "${AWS::StackName}-SGID"
